# Generated by Django 4.2.16 on 2025-02-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='prefixed_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='suffixed_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
