# Generated by Django 4.2.16 on 2025-02-25 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_management', '0002_leaverequest_medical_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave', models.IntegerField(default=25)),
                ('earned_leave', models.IntegerField(default=33)),
                ('half_pay_leave', models.IntegerField(default=20)),
                ('commuted_leave', models.IntegerField(default=20)),
                ('maternity_leave', models.IntegerField(default=180)),
                ('paternity_leave', models.IntegerField(default=10)),
                ('special_leave', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
