# Generated by Django 4.2.16 on 2025-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_leavebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='commuted_leave',
            field=models.IntegerField(default=10),
        ),
    ]
