# Generated by Django 4.2.16 on 2025-03-12 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_management', '0004_alter_leavebalance_commuted_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='InServiceCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('Inside Kerala', 'Inside Kerala'), ('National Level', 'National Level'), ('International Level', 'International Level')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
