# Generated by Django 4.2.16 on 2025-04-09 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_management', '0008_remove_leavebalance_commuted_leave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='special_leave',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
