# Generated by Django 4.2.16 on 2025-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0010_leaveapplication_medical_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='prefixed_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='suffixed_leave',
            field=models.BooleanField(default=False),
        ),
    ]
