# Generated by Django 4.2.16 on 2025-02-24 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('half_pay', 'Half Pay Leave'), ('commuted', 'Commuted Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('with_allowance', 'Leave with Allowance'), ('without_allowance', 'Leave without Allowance'), ('special', 'Special Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave', models.IntegerField(default=25)),
                ('earned_leave', models.IntegerField(default=0)),
                ('half_pay_leave', models.IntegerField(default=0)),
                ('commuted_leave', models.IntegerField(default=0)),
                ('maternity_leave', models.IntegerField(default=180)),
                ('paternity_leave', models.IntegerField(default=10)),
                ('leave_with_allowance', models.IntegerField(default=0)),
                ('leave_without_allowance', models.IntegerField(default=0)),
                ('special_leave', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
