# Generated by Django 4.2.16 on 2025-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_inservicecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inservicecourse',
            name='user',
        ),
        migrations.AlterField(
            model_name='inservicecourse',
            name='certificate',
            field=models.FileField(default='default_certificate.pdf', upload_to='certificates/'),
        ),
    ]
