# Generated by Django 4.2.16 on 2025-03-26 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_management', '0007_leaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='commuted_leave',
        ),
        migrations.AddField(
            model_name='inservicecourse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Earned Leave', 'Earned Leave'), ('Half Pay Leave', 'Half Pay Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Special Leave', 'Special Leave')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('half_pay', 'Half Pay Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('with_allowance', 'Leave with Allowance'), ('without_allowance', 'Leave without Allowance'), ('special', 'Special Leave')], max_length=20),
        ),
    ]
