# Generated by Django 4.2.16 on 2025-04-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0009_remove_leavebalance_special_leave_leavebalance_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='prefixed_leave',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='suffixed_leave',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
