# Generated by Django 5.2 on 2025-04-10 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inservicecourse',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inservicecourse',
            name='certificate',
            field=models.FileField(upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='inservicecourse',
            name='course_type',
            field=models.CharField(max_length=100),
        ),
    ]
