# Generated by Django 5.2 on 2025-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0013_inservicecourse_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inservicecourse',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='inservicecourse',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='inservicecourse',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inservicecourse',
            name='course_type',
            field=models.CharField(choices=[('Inside Kerala', 'Inside Kerala'), ('National Level', 'National Level'), ('International Level', 'International Level')], max_length=50),
        ),
    ]
