# Generated by Django 5.2 on 2025-04-10 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0014_remove_inservicecourse_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inservicecourse',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
