# Generated by Django 4.2.16 on 2025-04-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0015_inservicecourse_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='seen',
            new_name='is_read',
        ),
    ]
