# Generated by Django 4.2.16 on 2025-04-30 19:50

from django.db import migrations, models
import leave_management.models


from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0017_delete_leaveapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='current_year',
            field=models.PositiveIntegerField(default=2025),  # <-- hardcoded current year
        ),
    ]
