# Generated by Django 4.2.16 on 2025-04-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0018_alter_leavebalance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
