# Generated by Django 4.2.16 on 2025-04-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0019_leaverequest_is_deducted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='is_deducted',
            new_name='deduction_done',
        ),
        migrations.RemoveField(
            model_name='inservicecourse',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='inservicecourse',
            name='certificate',
            field=models.FileField(default=2, upload_to='course_certificates/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inservicecourse',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inservicecourse',
            name='course_type',
            field=models.CharField(choices=[('kerala', 'Inside Kerala'), ('national', 'National Level'), ('international', 'International Level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='earned_leave',
            field=models.PositiveIntegerField(default=33),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='half_pay_leave',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='maternity_leave',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='paternity_leave',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('half_pay', 'Half Pay Leave'), ('commuted', 'Commuted Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('special', 'Special Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='prefixed_leave',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='suffixed_leave',
            field=models.DateField(blank=True, null=True),
        ),
    ]
