# Generated by Django 4.2.16 on 2025-04-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0020_rename_is_deducted_leaverequest_deduction_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='prefixed_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='suffixed_leave',
            field=models.BooleanField(default=False),
        ),
    ]
