# Generated by Django 4.2.16 on 2025-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0021_alter_leaverequest_prefixed_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inservicecourse',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='course_certificates/'),
        ),
    ]
