# Generated by Django 4.2.16 on 2025-05-01 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0022_alter_inservicecourse_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inservicecourse',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
