# Generated by Django 4.2.16 on 2025-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0024_leaverequest_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
