# Generated by Django 4.2.16 on 2025-05-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0025_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='prefixed_leave',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='suffixed_leave',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='prefixed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='suffixed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
