# Generated by Django 4.2.16 on 2025-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0026_remove_leaverequest_prefixed_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='prefixed_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='suffixed_leave',
            field=models.BooleanField(default=False),
        ),
    ]
