# Generated by Django 4.2.16 on 2025-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0027_leaverequest_prefixed_leave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
