# Generated by Django 4.2.16 on 2025-05-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0028_rename_timestamp_notification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient_role',
        ),
    ]
