# Generated by Django 5.2 on 2025-05-07 08:39

import leave_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0029_remove_notification_recipient_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='year',
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='current_year',
            field=models.PositiveIntegerField(default=leave_management.models.get_current_year),
        ),
    ]
